### ISSUE TITLE
V2018.2 contains an old version of PyGame-lesson1.pptx

### ISSUE THREAD

**Issue by gregcorbett** [stfc/WorkExp-CompWorkshop#2]
That doesn't match the example code for that lesson. 

Can it eventually be updated with the version on Sharepoint? For the lesson this afternoon, having the most recent copy on the main computer will be sufficient (i.e. no need to make a new release for this afternoon).

**Comment by norealroots** [comment]
Thanks Greg, I'll update the release to v2018.3.
